# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-13 09:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='staff',
            field=models.ManyToManyField(blank=True, related_name='business_staff', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='region',
            name='RegionStaff',
            field=models.ManyToManyField(blank=True, related_name='Region_Staff', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='university',
            name='universityStaff',
            field=models.ManyToManyField(blank=True, related_name='UniversityStaff', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='university',
            name='universityStudents',
            field=models.ManyToManyField(blank=True, related_name='UniversityStudents', to=settings.AUTH_USER_MODEL),
        ),
    ]
