# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 02:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_businessemailformats'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businessemailformats',
            old_name='university',
            new_name='business',
        ),
    ]
