# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 06:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20160428_0305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessuser',
            name='avatarImage',
            field=models.ImageField(null=True, upload_to='images/avatars'),
        ),
        migrations.AlterField(
            model_name='student',
            name='avatarImage',
            field=models.ImageField(null=True, upload_to='images/avatars'),
        ),
    ]
