# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-13 07:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application_tests', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationtests',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='question',
            name='updated_by',
        ),
        migrations.AddField(
            model_name='applicationtests',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
