# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-26 02:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectplaces',
            name='projectRole',
        ),
        migrations.RemoveField(
            model_name='projectplaces',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='projectroles',
            name='roleType',
        ),
        migrations.RemoveField(
            model_name='projectroles',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='roles',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='projecttasks',
            name='project',
        ),
        migrations.RemoveField(
            model_name='projecttasks',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='projectPlaces',
        ),
        migrations.DeleteModel(
            name='projectRoles',
        ),
        migrations.DeleteModel(
            name='projects',
        ),
        migrations.DeleteModel(
            name='projectTasks',
        ),
    ]
