# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-29 08:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pod', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('percentageCompleted', models.IntegerField(default=0)),
                ('pod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pod.pod')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=30)),
                ('startdate', models.DateField(blank=True, null=True)),
                ('enddate', models.DateField(blank=True, null=True)),
                ('hours', models.IntegerField(default=0)),
                ('note', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('hours', models.IntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectRoleType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=200)),
                ('percentageCompleted', models.IntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='projectplaces',
            name='projectRole',
        ),
        migrations.RemoveField(
            model_name='projectplaces',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='projectroles',
            name='roleType',
        ),
        migrations.RemoveField(
            model_name='projectroles',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='projectroletypes',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='roles',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='projecttasks',
            name='project',
        ),
        migrations.RemoveField(
            model_name='projecttasks',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='projectPlaces',
        ),
        migrations.DeleteModel(
            name='projectRoles',
        ),
        migrations.DeleteModel(
            name='projectRoleTypes',
        ),
        migrations.DeleteModel(
            name='projects',
        ),
        migrations.DeleteModel(
            name='projectTasks',
        ),
        migrations.AddField(
            model_name='projectrole',
            name='roleType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.ProjectRoleType'),
        ),
        migrations.AddField(
            model_name='projectrole',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectplace',
            name='ProjectRole',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.ProjectRole'),
        ),
        migrations.AddField(
            model_name='projectplace',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
